# JuneERP Complete Docker Setup
version: '3.8'

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: juneerp
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secure_password
    volumes:
      - ./database/01-complete-schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./database/02-complete-data.sql:/docker-entrypoint-initdb.d/02-data.sql
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d juneerp"]
      interval: 30s
      timeout: 10s
      retries: 3

  juneerp:
    build: .
    environment:
      DATABASE_URL: postgresql://admin:secure_password@postgres:5432/juneerp
      NODE_ENV: production
    ports:
      - "5000:5000"
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - juneerp

volumes:
  postgres_data:
